package com.example.geofencing;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

@Entity(tableName = "CORDINATES")
public class Cordinates {

    //autogenerated unique id for each cordinate ... so its and primary key
    @PrimaryKey(autoGenerate = true)
    public int id;

    //latitude
    @ColumnInfo(name = "LAT")
    public Double latitude;

    //longitude
    @ColumnInfo(name = "LONG")
    public Double longitude;

    //transition
    @ColumnInfo(name = "TRANSITION")
    public int transition;

    //timestamp
    @ColumnInfo(name = "TIMESTAMP")
    public Long timestamp;


    //getter and setters
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public int getTransition() {
        return transition;
    }

    public void setTransition(int transition) {
        this.transition = transition;
    }

    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }
}
